plugins {
    id 'com.android.application'
}

android {
    namespace 'com.picoxr.librarywallpaper'
    compileSdk 34

    defaultConfig {
        applicationId 'com.picoxr.librarywallpaper'
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
    }
}

dependencies {
    compileOnly files('libs/vector-legacy-xposed-api.jar')
    testImplementation 'junit:junit:4.13.2'
}
